<applet codebase="/ircfiles/" code=IRCApplet.class archive="irc.jar,pixx.jar" width=640 height=400>
<param name="CABINETS" value="irc.cab,securedirc.cab,pixx.cab">

<param name="nick" value="Anonymous">
<param name="alternatenick" value="Anon???">
<param name="name" value="TF93 User">
<param name="host" value="irc.aceirc.org">
<param name="gui" value="pixx">
<param name="quitmessage" value="Where the extraordinary is just another day at the office.">
<param name="asl" value="true">
<param name="command1" value="/join #TF93">


<param name="style:bitmapsmileys" value="true">
<param name="style:smiley1" value=":) img/sourire.gif">
<param name="style:smiley2" value=":-) img/sourire.gif">
<param name="style:smiley3" value=":-D img/content.gif">
<param name="style:smiley4" value=":d img/content.gif">
<param name="style:smiley5" value=":-O /irc/img/OH-2.gif">
<param name="style:smiley6" value=":o /irc/img/OH-1.gif">
<param name="style:smiley7" value=":-P /irc/img/langue.gif">
<param name="style:smiley8" value=":p /irc/img/langue.gif">
<param name="style:smiley9" value=";-) /irc/img/clin-oeuil.gif">
<param name="style:smiley10" value=";) /irc/img/clin-oeuil.gif">
<param name="style:smiley11" value=":-( /irc/img/triste.gif">
<param name="style:smiley12" value=":( /irc/img/triste.gif">
<param name="style:smiley13" value=":-| /irc/img/OH-3.gif">
<param name="style:smiley14" value=":| /irc/img/OH-3.gif">
<param name="style:smiley15" value=":'( /irc/img/pleure.gif">
<param name="style:smiley16" value=":$ /irc/img/rouge.gif">
<param name="style:smiley17" value=":-$ /irc/img/rouge.gif">
<param name="style:smiley18" value="(H) /irc/img/cool.gif">
<param name="style:smiley19" value="(h) /irc/img/cool.gif">
<param name="style:smiley20" value=":-@ /irc/img/enerve1.gif">
<param name="style:smiley21" value=":@ /irc/img/enerve2.gif">
<param name="style:smiley22" value=":-S /irc/img/roll-eyes.gif">
<param name="style:smiley23" value=":s /irc/img/roll-eyes.gif">
<param name="style:floatingasl" value="true">

<param name="pixx:highlight" value="true">
<param name="pixx:highlightnick" value="true">

</applet>
