<p>Welcome to SGMS</p>

<h2>News</h2>
<?php
foreach($this->headlines as $headline)
{
?>
<ul>
<?php

if(isset($headline['logo']))
{
?>	<img src="/images/news/<?php echo $headline['logo']; ?>" style="float:left"/>
<?php
}
?><a href="/news/article/id/<?php echo $headline['id']; ?>"><?php echo $headline['title']; ?></a>
<p><?php echo $headline['summary']; ?> (<a href="/news/article/id/<?php echo $headline['id']; ?>">Read more...</a>)</p>
</ul>
<?php
}
?>
<br clear="both" />
<h2>Open Positions</h2>

<h2>Stats</h2>
<ul>
<li><?= $this->statistics['games']; ?> Games</li>
<li><?= $this->statistics['accounts']; ?> Accounts</li>
<li><?= $this->statistics['characters']; ?> Characters</li>
</ul>
