<p>This is where you edit your account.</p>

<fieldset> 
<legend>Account Details</legend> 
<div>
<label>Username</label>
$username - <strike>Request username change</strike>
</div>
<div>
<label>Email Address</label>
$email - <strike>Change Email</strike>
</div>
<div>
<label>Reset Password</label>
<strike><a href="/account/resetpassword">Click here to reset password</a></strike>
</div>
</fieldset>
<br />
<fieldset>
<legend>Profile</legend>
<div>
<label>location</label>
$location
</div>

</fieldset>
<br />
<fieldset>
<legend>Instant Message</legend>
<div>
<label>MSN</label>
$msn
</div>
<div>
<label>AOL</label>
$aol
</div>
<div>
<label>Yahoo</label>
$yahoo
</div>
<div>
<label>ICQ</label>
$icq
</div>
<div>
<label>Google Talk</label>
$gtalk
</div>
<div>
<label>Skype</label>
$skype
</div>
</fieldset>
<br />
<fieldset>
<legend>Options</legend>
