<script type="text/javascript">
	$(function() {
		$("#tabs").tabs();
	});
	</script>

<p>This is where you modify your account</p>

<div id="tabs">
	<ul>
		<li><a href="#tab1">Nunc tincidunt</a></li>
		<li><a href="#tab2">Proin dolor</a></li>
		<li><a href="#tab3">Aenean lacinia</a></li>
	</ul>
	<div id="tab1">
		Modify Email & Password
	</div>
	
	<div id="tab2">
		Contact preferences
	</div>
</div>
