<?php echo $this->doctype(); ?>
<html>
<head>
<?php echo $this->headTitle(); ?>
<?php echo $this->headLink(); ?>
<?php 
if($this->jQuery()->isEnabled())
{
	$this->jQuery()->setLocalPath($this->baseUrl().'/js/jquery/jquery-1.4.2.js')
		       ->setUiLocalPath($this->baseUrl().'/js/jquery/ui/jquery-ui-1.8.1.custom.js')
		       ->addStyleSheet($this->baseUrl().'/js/jquery/css/smoothness/jquery-ui-1.8.1.custom.css');
	echo $this->jQuery();
}
?>
<?php
/*
<script type="text/javascript">
	$(function() {
		$("#dialog").dialog();
	});
	</script>
*/
?>
</head>

<body>

<div id="title">
Single Abstract Noun
</div>

<div id="menu">
	<?php echo $this->navigation(); ?>
</div>
<div id="search">
<?php
// echo new forms_MiniSearch();

?>
</div>
<div id="content">
<?php echo $this->layout()->content; ?>
</div>

<?php
if(isset($messages))
{
	foreach($messages as $message)
	{
		var_dump($message);
	}
}

// var_dump(Zend_Session::getSaveHandler());
?>

</body>

</html>
