<?php echo $this->doctype(); ?>
<html>
<head>
<?php echo $this->headTitle(); ?>
<?php echo $this->headLink(); ?>
<?php 
if($this->jQuery()->isEnabled())
{
	$this->jQuery()->setLocalPath($this->baseUrl().'/js/jquery/jquery-1.4.2.js')
		       ->setUiLocalPath($this->baseUrl().'/js/jquery/ui/jquery-ui-1.8.1.custom.js')
		       ->addStyleSheet($this->baseUrl().'/js/jquery/css/smoothness/jquery-ui-1.8.1.custom.css');
	echo $this->jQuery();
}
?>
<?php
/*
<script type="text/javascript">
	$(function() {
		$("#dialog").dialog();
	});
	</script>
*/
?>
</head>

<body>
<?php
if(getenv('APPLICATION_ENV') == 'development')
{

/*
echo $this->dialogContainer('dialog', 'This is the development version of Task Force 93\'s Website. The information contained here
is probably incorrect. Please head
to <a href="http://www.taskforce93.com">http://www.taskforce93.com/</a> for the live site.');
*/
}
?>

<div id="title">
<img src="/images/banner.jpg" alt="Task Force 93" />
</div>

<div id="menu">
	<?php echo $this->navigation(); ?>
	<? /* php echo $this->profileLink(); */?>
</div>
<div id="search">
<?php
// echo new forms_MiniSearch();

?>
</div>
<div id="content">
<?php echo $this->layout()->content; ?>
</div>

<?php
if(isset($messages))
{
	foreach($messages as $message)
	{
		var_dump($message);
	}
}

// var_dump(Zend_Session::getSaveHandler());
?>

<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
try {
var pageTracker = _gat._getTracker("UA-15716919-2");
pageTracker._trackPageview();
} catch(err) {}</script>

</body>

</html>
